#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl,
# it must return a page that contains the string Hello World!
# script that configures a new Ubuntu machine to respect above requirements
# (this script will be run on the server itself)

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/nginx-html/index.html
service nginx start
