#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl,
# it must return a page that contains the string Hello World!
# script that configures a new Ubuntu machine to respect above requirements
# (this script will be run on the server itself)
sudo apt-get update
if [ ! -x /usr/bin/nginx ]; then 
     sudo apt-get -y install nginx
fi

if [ ! -d /var/www/nginx-html ]; then
     sudo mkdir -p /var/www/nginx-html
     touch /var/www/nginx-html/index.html
     echo "Hello World!" > /var/www/nginx-html/index.html
fi
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/nginx-html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
service nginx restart
