#!/usr/bin/env bash
# script that Configures my Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
if [ ! -f /var/www/nginx-html/404.html ]; then
    touch /var/www/nginx-html/404.html
    echo -e "Ceci n'est pas une page\n" > /var/www/nginx-html/404.html
fi
sed -i 'server_name__;a \
\
    location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    } \
\
    error_page 404 /404.html;
    location /404 {
        root /var/www/nginx-html;
        internal;
}' /etc/nginx/sites-available/default
service nginx restart
